### ISSUE TITLE
Problems with installation - building step

### ISSUE THREAD

**Issue by rbcan** [fwhelan/coinfinder#1]
Hello,

I am trying to install coinfinder and after some trouble shooting managed to run the first step successfully. But when I run

`cmake --build .`

I get the following error. Any idea what this may be? Thanks in advance!

```
[  6%] Building CXX object CMakeFiles/coinfinder.dir/coinfind-code/main.cpp.o
/home/rebecca/work/tools/coinfinder-master/coinfind-code/main.cpp: In function ‘int main(int, const char**)’:
/home/rebecca/work/tools/coinfinder-master/coinfind-code/main.cpp:181:33: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
          system(syscall.c_str());
                                 ^
[ 13%] Building CXX object CMakeFiles/coinfinder.dir/coinfind-code/id_lookup.cpp.o
[ 20%] Building CXX object CMakeFiles/coinfinder.dir/coinfind-code/dataset.cpp.o
[ 26%] Building CXX object CMakeFiles/coinfinder.dir/coinfind-code/coincidence.cpp.o
[ 33%] Building CXX object CMakeFiles/coinfinder.dir/coinfind-code/connectivity.cpp.o
[ 40%] Building CXX object CMakeFiles/coinfinder.dir/coinfind-code/binomial_test.cpp.o
[ 46%] Building CXX object CMakeFiles/coinfinder.dir/coinfind-code/significance.cpp.o
/home/rebecca/work/tools/coinfinder-master/coinfind-code/significance.cpp: In static member function ‘static double Significance::correct(double, ECorrection, int)’:
/home/rebecca/work/tools/coinfinder-master/coinfind-code/significance.cpp:26:23: error: ‘logic_error’ is not a member of ‘std’
                 throw std::logic_error("Infinite significance level. This is probably due to an earlier error.");
                       ^
/home/rebecca/work/tools/coinfinder-master/coinfind-code/significance.cpp:40:19: error: ‘logic_error’ is not a member of ‘std’
             throw std::logic_error("Invalid switch on Significance::correct(correction).");
                   ^
make[2]: *** [CMakeFiles/coinfinder.dir/coinfind-code/significance.cpp.o] Error 1
make[1]: *** [CMakeFiles/coinfinder.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by fwhelan** [comment]
Hi rbcan. Sorry that you’re running into issues. I unfortunately can’t reproduce this error on my Ubuntu machine. I’ll have access to a MacBook later today, but I’m wondering if this might be related to the version of `gcc`- what version are you running (`gcc -v`)? Are you installing coinfinder on a Mac, Ubuntu etc.?

**Comment by rbcan** [comment]
Dear fwhelan,

thank you very much for your response. I am trying to install this on Ubuntu 14.04. My gcc version is 4.8.4 (see below). Do you recommend another gcc version?
```
gcc -v

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.4' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.4)
```

**Comment by rbcan** [comment]
Update: I have tried with a newer gcc version (9.1.0), still on my Ubuntu 14.04

I now get different error messages but maybe they are more meaningful to you?

```
Scanning dependencies of target coinfinder
[  6%] Building CXX object CMakeFiles/coinfinder.dir/coinfind-code/main.cpp.o
/home/rebecca/work/tools/coinfinder-master/coinfind-code/main.cpp: In function ‘int main(int, const char**)’:
/home/rebecca/work/tools/coinfinder-master/coinfind-code/main.cpp:181:16: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
  181 |          system(syscall.c_str());
      |          ~~~~~~^~~~~~~~~~~~~~~~~
[  6%] Building CXX object CMakeFiles/coinfinder.dir/coinfind-code/id_lookup.cpp.o
[  6%] Building CXX object CMakeFiles/coinfinder.dir/coinfind-code/dataset.cpp.o
[  6%] Building CXX object CMakeFiles/coinfinder.dir/coinfind-code/coincidence.cpp.o
[  6%] Building CXX object CMakeFiles/coinfinder.dir/coinfind-code/connectivity.cpp.o
[  6%] Building CXX object CMakeFiles/coinfinder.dir/coinfind-code/binomial_test.cpp.o
[  6%] Building CXX object CMakeFiles/coinfinder.dir/coinfind-code/significance.cpp.o
[  6%] Building CXX object CMakeFiles/coinfinder.dir/coinfind-code/parameters.cpp.o
[  6%] Building CXX object CMakeFiles/coinfinder.dir/coinfind-code/elements.cpp.o
/home/rebecca/work/tools/coinfinder-master/coinfind-code/elements.cpp: In member function ‘Alpha* Alpha::get_alpha(std::string)’:
/home/rebecca/work/tools/coinfinder-master/coinfind-code/elements.cpp:98:1: warning: no return statement in function returning non-void [-Wreturn-type]
   98 | }
      | ^
[  6%] Building CXX object CMakeFiles/coinfinder.dir/coinfind-code/test_cases.cpp.o
[  6%] Building CXX object CMakeFiles/coinfinder.dir/coinfind-code/bugfix.cpp.o
[  6%] Building CXX object CMakeFiles/coinfinder.dir/coinfind-code/lineage.cpp.o
/home/rebecca/work/tools/coinfinder-master/coinfind-code/lineage.cpp: In static member function ‘static int Lineage::run(DataSet&, const string&, const string&, const string&, const string&, int, bool, const string&)’:
/home/rebecca/work/tools/coinfinder-master/coinfind-code/lineage.cpp:47:10: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
   47 |    system(syscall.c_str());
      |    ~~~~~~^~~~~~~~~~~~~~~~~
[  6%] Building CXX object CMakeFiles/coinfinder.dir/coinfind-code/gexf.cpp.o
[  6%] Building CXX object CMakeFiles/coinfinder.dir/coinfind-code/network.cpp.o
/home/rebecca/work/tools/coinfinder-master/coinfind-code/network.cpp: In static member function ‘static int Network::run(DataSet&, const string&, const string&, const string&, const string&, bool, const string&)’:
/home/rebecca/work/tools/coinfinder-master/coinfind-code/network.cpp:20:10: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
   20 |    system(syscall.c_str());
      |    ~~~~~~^~~~~~~~~~~~~~~~~
/home/rebecca/work/tools/coinfinder-master/coinfind-code/network.cpp:40:31: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
   40 |                         system(syscall.c_str());
      |                         ~~~~~~^~~~~~~~~~~~~~~~~
[  6%] Linking CXX executable coinfinder
/usr/local/lib/libpython3.6m.a(thread.o): In function `PyThread_create_key':
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:617: undefined reference to `pthread_key_create'
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:622: undefined reference to `pthread_key_delete'
/usr/local/lib/libpython3.6m.a(thread.o): In function `PyThread_set_key_value':
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:645: undefined reference to `pthread_setspecific'
/usr/local/lib/libpython3.6m.a(thread.o): In function `PyThread_delete_key':
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:632: undefined reference to `pthread_key_delete'
/usr/local/lib/libpython3.6m.a(thread.o): In function `PyThread_get_key_value':
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:652: undefined reference to `pthread_getspecific'
/usr/local/lib/libpython3.6m.a(thread.o): In function `PyThread_start_new_thread':
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:211: undefined reference to `pthread_attr_setstacksize'
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:221: undefined reference to `pthread_create'
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:237: undefined reference to `pthread_detach'
/usr/local/lib/libpython3.6m.a(thread.o): In function `_pythread_pthread_set_stacksize':
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:595: undefined reference to `pthread_attr_setstacksize'
/usr/local/lib/libpython3.6m.a(thread.o): In function `PyThread_delete_key_value':
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:638: undefined reference to `pthread_setspecific'
/usr/local/lib/libpython3.6m.a(thread.o): In function `PyThread_allocate_lock':
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:290: undefined reference to `sem_init'
/usr/local/lib/libpython3.6m.a(thread.o): In function `PyThread_free_lock':
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:315: undefined reference to `sem_destroy'
/usr/local/lib/libpython3.6m.a(thread.o): In function `PyThread_acquire_lock_timed':
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:352: undefined reference to `sem_trywait'
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:354: undefined reference to `sem_wait'
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:352: undefined reference to `sem_trywait'
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:352: undefined reference to `sem_trywait'
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:350: undefined reference to `sem_timedwait'
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:350: undefined reference to `sem_timedwait'
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:354: undefined reference to `sem_wait'
/usr/local/lib/libpython3.6m.a(thread.o): In function `PyThread_release_lock':
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:396: undefined reference to `sem_post'
/usr/local/lib/libpython3.6m.a(thread.o): In function `PyThread_acquire_lock_timed':
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:352: undefined reference to `sem_trywait'
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:354: undefined reference to `sem_wait'
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:352: undefined reference to `sem_trywait'
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:352: undefined reference to `sem_trywait'
/home/rebecca/work/tools/Python-3.6.3/Python/thread_pthread.h:354: undefined reference to `sem_wait'
/usr/local/lib/libpython3.6m.a(posixmodule.o): In function `os_forkpty_impl':
/home/rebecca/work/tools/Python-3.6.3/./Modules/posixmodule.c:5905: undefined reference to `forkpty'
/usr/local/lib/libpython3.6m.a(posixmodule.o): In function `os_openpty_impl':
/home/rebecca/work/tools/Python-3.6.3/./Modules/posixmodule.c:5811: undefined reference to `openpty'
/usr/local/lib/libpython3.6m.a(signalmodule.o): In function `signal_pthread_kill_impl':
/home/rebecca/work/tools/Python-3.6.3/./Modules/signalmodule.c:1121: undefined reference to `pthread_kill'
/usr/local/lib/libpython3.6m.a(signalmodule.o): In function `signal_pthread_sigmask_impl':
/home/rebecca/work/tools/Python-3.6.3/./Modules/signalmodule.c:857: undefined reference to `pthread_sigmask'
/usr/local/lib/libpython3.6m.a(faulthandler.o): In function `faulthandler_thread':
/home/rebecca/work/tools/Python-3.6.3/./Modules/faulthandler.c:561: undefined reference to `pthread_sigmask'
/usr/local/lib/libpython3.6m.a(dynload_shlib.o): In function `_PyImport_FindSharedFuncptr':
/home/rebecca/work/tools/Python-3.6.3/./Python/dynload_shlib.c:95: undefined reference to `dlopen'
/home/rebecca/work/tools/Python-3.6.3/./Python/dynload_shlib.c:126: undefined reference to `dlsym'
/home/rebecca/work/tools/Python-3.6.3/./Python/dynload_shlib.c:101: undefined reference to `dlerror'
/home/rebecca/work/tools/Python-3.6.3/./Python/dynload_shlib.c:82: undefined reference to `dlsym'
/home/rebecca/work/tools/Python-3.6.3/./Python/dynload_shlib.c:95: undefined reference to `dlopen'
collect2: error: ld returned 1 exit status
make[2]: *** [coinfinder] Error 1
make[1]: *** [CMakeFiles/coinfinder.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by fwhelan** [comment]
Sorry for the delay- I'm done travelling now so I'll be more responsive.

Okay, so I might need to put a restraint on the version of `gcc`- I'll look into that momentarily.

I just pushed a small change to the `CMakeLists.txt` file with a fix that has solved a similar problem to the above for others in the past. It doesn't break my ability to install on the Ubuntu and Mac machines I have access to, but I can't say for certain that it will solve your issue. Would you mind cloning the repository again and trying it out? Thanks so much for your patience!

**Comment by rbcan** [comment]
Thanks so much for getting back to me. Unfortunately this did not fix the error (same ones as the ones above). It looks like it has some problems to link or find PyThread. Do you think my python installation could be the issue?

Thank you :)

**Comment by fwhelan** [comment]
I'm running `Python-3.7.4` and `Python-3.6.8` without any issues so I don't think so. I think it's an issue with the right libraries being found by the compiler such that the multithreading references (`pthread_key_create`, `pthread_key_delete` etc.) are defined. Unfortunately, this isn't an area I have great experience in so there might be a bit more back and forth.

I've added the following to `CMakeLists.txt` based on this discussion https://cmake.org/pipermail/cmake/2016-February/062729.html
```
find_package(Threads)
target_link_libraries(coinfinder ${CMAKE_THREAD_LIBS_INIT})
```

Let me know if that helps! If not, could you paste the output of `cmake -DCMAKE_BUILD_TYPE=Release .` here please?

**Comment by rbcan** [comment]
Thanks for that! This removed most of the errors I got - yay :) 
Now the only ones that are still appearing are the ones below. I noticed this is a slightly different folder than the libraries. Do you also have a brilliant fix for those? 

```
[100%] Linking CXX executable coinfinder
/usr/local/lib/libpython3.6m.a(posixmodule.o): In function `os_forkpty_impl':
/home/rebecca/work/tools/Python-3.6.3/./Modules/posixmodule.c:5905: undefined reference to `forkpty'
/usr/local/lib/libpython3.6m.a(posixmodule.o): In function `os_openpty_impl':
/home/rebecca/work/tools/Python-3.6.3/./Modules/posixmodule.c:5811: undefined reference to `openpty'
collect2: error: ld returned 1 exit status
make[2]: *** [coinfinder] Error 1
make[1]: *** [CMakeFiles/coinfinder.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by fwhelan** [comment]
Progress! Alrighty, could you give the newest version a try? So sorry that you've found so many bugs- the problem with new software :)).

**Comment by rbcan** [comment]
I am sorry, this doesn't work for me. I am trying to play with google and changing things up but so far no success (keep trying though). If you have another idea I am happy to add any likes to CMakeLists.txt that you can think of. 

No worries about the bugs, I am really excited if this works in the end ;)

**Comment by rbcan** [comment]
I figured it out! :) I am so excited - it was successfully built now. I used your trick but adapted it a bit after a lot of googling. Here is what worked for me. New lines are these but later in the file (after linking python and other libraries)

```
target_link_libraries(coinfinder "-lutil")
set(CMAKE_MODULE_LINKER_FLAGS "-lutil")
```

 I commented out your Module-linker (#set(CMAKE_MODULE_LINKER_FLAGS "-lutil") further up. So below you see the block where I inserted the lines

```
#dlopen, dlerror, dlsym undefined reference error fix
target_link_libraries(coinfinder ${CMAKE_DL_LIBS})
target_link_libraries(coinfinder "-lutil")
set(CMAKE_MODULE_LINKER_FLAGS "-lutil")
find_package(Threads)
target_link_libraries(coinfinder ${CMAKE_THREAD_LIBS_INIT})

```

Thanks SO much for helping me to compile this. I will now give it a go!

**Comment by fwhelan** [comment]
That's great news! Thanks so much for your help! The adjustments you made to your `CMakeLists.txt` doesn't break anything on my 2 test machines, so I've implemented them into `coinfinder` for future users. Thanks for contributing, and for your patience with these bugs!

**Comment by nishantgerald** [comment]
For anyone else getting errors on the --build step for significance.cpp.o:
switching to gcc v 9.2.0 should fix it (make sure you repeat the make step with the new GCC)
