### ISSUE TITLE
OpenMP issue when building on linux-ubuntu

### ISSUE THREAD

**Issue by seretol** [fwhelan/coinfinder#3]
Hi Guys,

When building in linux, I had the following error:
CMake Warning at CMakeLists.txt:57 (find_package):
  By not providing "FindOPENMP.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OPENMP", but
  CMake did not find one.

  Could not find a package configuration file provided by "OPENMP" with any
  of the following names:

    OPENMPConfig.cmake
    openmp-config.cmake

  Add the installation prefix of "OPENMP" to CMAKE_PREFIX_PATH or set
  "OPENMP_DIR" to a directory containing one of the above files.  If "OPENMP"
  provides a separate development package or SDK, be sure it has been
  installed.

To make it work, I forked your repo and changed the CMakeLists.txt. I removed all the code from if(APPLE) onwards and replaced it with 
FIND_PACKAGE(OpenMP)
IF(OPENMP_FOUND)
  SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
  SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
ENDIF()

I am unfortunately not competent enough to change the CMakeLists.txt and give you a pull request that works for both Apple and Linux, but I hope the above helps.

Best,

-oli

**Comment by fwhelan** [comment]
Hi oli,

Thanks so much for your comment and for finding a fix for this! I've implemented your changes in a way that doesn't break my Mac and Linux test machines and hopefully will be more versatile moving forward.

Thank you!

**Comment by seretol** [comment]
Hi Fiona,

I had a look at the latest changes and I am still getting the error:
﻿CMake Warning at CMakeLists.txt:57 (find_package):
  By not providing "FindOPENMP.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OPENMP", but
  CMake did not find one.

  Could not find a package configuration file provided by "OPENMP" with any
  of the following names:

    OPENMPConfig.cmake
    openmp-config.cmake

 Add the installation prefix of "OPENMP" to CMAKE_PREFIX_PATH or set
  "OPENMP_DIR" to a directory containing one of the above files.  If "OPENMP"
  provides a separate development package or SDK, be sure it has been
  installed.


On ubuntu, I installed ﻿libomp-dev, have I got the dependency right?



Best,

-oli

**Comment by fwhelan** [comment]
Hi oli,

Hmm that's strange. Are you able to identify the differences in the `CMakeLists.txt` that you got working from the `CMakeLists.txt` that comes with `coinfinder`? Or maybe more simply, could you paste the contents of the `CMakeLists.txt` that you got working here?

**Comment by seretol** [comment]
Hi Fiona,

There are 2 things causing problems.
1/ the case used in find_package:
﻿find_package(OpenMP) works
﻿find_package(OPENMP) does not

2/ include_directories("${OPENMP_INCLUDES}") fails with the error:
﻿CMake Error at CMakeLists.txt:60 (include_directories):
  include_directories given empty-string as include directory.


So after correcting the CMakeLists.txt, I end up with ﻿

find_package(OpenMP)

if (OPENMP_FOUND)
    #include_directories("${OPENMP_INCLUDES}")
    #include_directories("/usr/local/include" "/usr/local/opt/llvm/include")
    link_directories("${OPENMP_LIBRARIES}")
    #link_directories("/usr/local/lib" "/usr/local/opt/llvm/lib")
    set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
    set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
    # set (CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
endif()

Best,

-oli

**Comment by fwhelan** [comment]
Hi seretol,

Apologies for missing these the first time. Does the newest push help?

**Comment by seretol** [comment]
Hi Fiona,

They did, so I think the problem is fixed.
Thanks for all your help regarding this.

Best,

-oli
