### ISSUE TITLE
getting error while generating coincidence heatmap

### ISSUE THREAD

**Issue by aryasuresh234** [fwhelan/coinfinder#8]
Hello
I am getting the following error while running the program. Can you please help me resolve this?
Calculating lineage dependence...
Generate coincidence heatmap...
ERROR MESSAGE FROM R: 
Error in read.newick(opt$phylogeny) : 
  could not find function "read.newick"
Execution halted
Thank you

**Comment by fwhelan** [comment]
Hi aryasuresh234,

Do you have the `phytools` package installed in `R`? It looks like coinfinder isn't able to use `phytools`'s read.newick function.

**Comment by aryasuresh234** [comment]
I have installed phytools, still was showing the error. Once i modified the script to include import library for phytools it is working smoothly. Thank you
Arya

**Comment by fwhelan** [comment]
Ah my fault, good spot!

Let me know if you run into any further issues.

**Comment by aryasuresh234** [comment]
Hello
I am facing a new error running the software. Can you please help me fix this?
Bonferroni significance correction, given 10573101 tests, the significance level has been reduced from 0.05 to 4.72898e-09.
Running analyses...
Calculating lineage dependence...
Generate coincidence heatmap...
Generate network...
No such file or directory
All done!
-Arya

**Comment by fwhelan** [comment]
Hi Arya- I think that this is an issue that I fixed in a recent push to the repository. Would you be able to confirm that you're using the most recent version of the software with the newest bug fixes? Thanks!!

**Comment by aryasuresh234** [comment]
Hi Fiona!
I downloaded the current version again from github and tried running again, but still getting the same error.
The command I used was:
**./coinfinder -i gene_presence_absence.csv -I -p RAxML_bestTree.ecoli  -o ecoli_coinfinder_2 --associate -x 4**

**Comment by aryasuresh234** [comment]
Hi Fiona
I just did a rerun with -v so that I can see the error. This is the error I am getting:
Generate coincidence heatmap...
Generate network...
Error: Gexf could not find the alpha name group_890 in the components file.
No such file or directory
All done!
I thought it might help you to troubleshoot it easier. I used the same command that I have given in the previous comment. 
-Arya

**Comment by fwhelan** [comment]
Hi Arya,

Sorry that you're running into so many issues. Would it be possible for me to get a copy of your -i and -p inputs to do some debugging with?

**Comment by aryasuresh234** [comment]
Hi Fiona
Sorry for the late reply. 
I can send you a copy of my input files if that will help you in debugging. Can you please provide me an email id to which i can send the same to?

**Comment by fwhelan** [comment]
Hi Arya,
I've just added my email to my github profile ( https://github.com/fwhelan )- feel free to send the files on and we'll get this sorted for you!

**Comment by fwhelan** [comment]
Hi Arya,
Thanks for sending on your data. I just ran it through the newest version of Coinfinder (with the conda install) and it worked okay. I'm wondering if the issue you were encountering is from a bug that I've fixed in the last 1-2 months.
Would you be able to install the newest Coinfinder (either by pulling the latest from github or installing via conda- whatever's easiest for you) and let me know if that solves your problem?

Thanks,
Fiona

**Comment by fwhelan** [comment]
I'm going to close this due to inactivity, but please feel free to open it again if you're still having issues.
